### ISSUE TITLE
codedoc check fails on ssh cloned repos

### ISSUE THREAD

**Issue by uloco** [CONNECT-platform/codedoc-cli#6]
Codedoc check gives me this error, although my repo is setup correctly in the `config.ts`

```
# Checking GitHub configuration ...
#
# WARNING::
# Your CODEDOC config indicates GitHub integration, but
# your project folder is not in sync with a GitHub repository.
#
# You can fix this by modifying .codedoc/config.ts
#
# Read https://codedoc.cc/docs/config/misc#github-integration for more information.
#
```

I looked up into your utils github info file and it seems the regex provided is not respecting any repositories cloned with ssh. The url changes here for ssh cloned repositories in this format (e.g. for me): `git@github.com:uloco/uloco.coding.blog.git`

**Comment by loreanvictor** [comment]
thats correct! the PR seems to be properly fixing the issue as well, will test later today and roll out a new version, thanks!
